"""Hypothesis Chain Generator — Architecture v2.

Generates three classes of hypotheses that the base HypothesisEngine misses:

1. Transitive / chained hypotheses
   When A→B and B→C are confirmed, generate "A indirectly affects C"
   and "if A increases then C changes via B".

2. Contradiction-driven mediator hypotheses
   When (A→B, positive) and (A→B, negative) have both been observed,
   generate "the effect of A on B is mediated by a third variable".

3. Diversity-enforced exploration hypotheses
   When >30% of all hypotheses involve the same concept, force generation
   of hypotheses about under-represented domains/concepts.

Usage
-----
    gen = HypothesisChainGenerator()

    new_hyps = gen.run(
        causal_rules=memory.get_causal_rules(),
        existing_hypotheses=hypotheses,
        knowledge_graph=knowledge_graph,
        current_tick=tick,
    )
    hypotheses.extend(new_hyps)
"""

from __future__ import annotations

import logging
import time
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Set, Tuple

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

MIN_CHAIN_CONFIDENCE: float = 0.25    # both links must exceed this
MEDIATOR_FLIP_THRESHOLD: int = 2      # how many sign-flips trigger a mediator hyp
DIVERSITY_DOMINANCE_THRESHOLD: float  = 0.30   # if one concept > 30% → force diversity
MAX_NEW_HYPS_PER_TICK: int = 8        # cap to avoid hypothesis explosion


# ---------------------------------------------------------------------------
# Data class
# ---------------------------------------------------------------------------

@dataclass
class ChainHypothesis:
    """A hypothesis generated by chaining or contradiction analysis."""
    rule:                   str
    concepts:               List[str]
    confidence:             float
    supporting_evidence:    int
    contradicting_evidence: int
    chain_type:             str     # "transitive" | "mediator" | "diversity"


# ---------------------------------------------------------------------------
# Main class
# ---------------------------------------------------------------------------

class HypothesisChainGenerator:
    """Generates richer hypotheses from existing causal knowledge.

    Designed to be called after InterventionCausalDiscovery runs each tick.
    Keeps track of which hypotheses it has already generated to avoid duplicates.
    """

    def __init__(self) -> None:
        self._generated: Set[str] = set()       # rule strings already generated
        self._flip_count: Dict[Tuple[str, str], int] = defaultdict(int)
        self._last_directions: Dict[Tuple[str, str], str] = {}

    def run(
        self,
        causal_rules:         List,   # CausalRuleRecord
        existing_hypotheses:  List,   # Hypothesis
        knowledge_graph,              # KnowledgeGraph (for graph traversal)
        current_tick:         int,
    ) -> List[ChainHypothesis]:

        new_hyps: List[ChainHypothesis] = []

        new_hyps.extend(self._transitive_hyps(causal_rules))
        new_hyps.extend(self._mediator_hyps(causal_rules))
        new_hyps.extend(self._diversity_hyps(existing_hypotheses + new_hyps, causal_rules))  # type: ignore[arg-type]

        # Deduplicate against existing + already generated
        existing_rules = {getattr(h, "rule", "") for h in existing_hypotheses}
        result: List[ChainHypothesis] = []
        for h in new_hyps:
            if h.rule in self._generated:
                continue
            if h.rule in existing_rules:
                continue
            self._generated.add(h.rule)
            result.append(h)
            if len(result) >= MAX_NEW_HYPS_PER_TICK:
                break

        if result:
            logger.info(
                "[hyp_chain] tick=%d generated=%d types=%s",
                current_tick,
                len(result),
                Counter(h.chain_type for h in result),
            )

        return result

    # ── Transitive hypotheses ─────────────────────────────────────────────────

    def _transitive_hyps(self, causal_rules: List) -> List[ChainHypothesis]:
        """A→B, B→C → generate 'A indirectly affects C'."""
        # Index: effect → list of rules that produce this effect
        effect_index: Dict[str, List] = defaultdict(list)
        cause_index:  Dict[str, List] = defaultdict(list)
        for rule in causal_rules:
            if rule.confidence >= MIN_CHAIN_CONFIDENCE:
                effect_index[rule.effect].append(rule)
                cause_index[rule.cause].append(rule)

        hyps: List[ChainHypothesis] = []
        seen: Set[Tuple[str, str]] = set()

        for rule_ab in causal_rules:
            if rule_ab.confidence < MIN_CHAIN_CONFIDENCE:
                continue
            a, b = rule_ab.cause, rule_ab.effect
            for rule_bc in effect_index.get(b, []):
                c = rule_bc.cause if rule_bc.effect == b else rule_bc.effect
                # rule_bc must go FROM b TO c
                if rule_bc.cause != b:
                    continue
                c = rule_bc.effect
                if c == a:
                    continue   # circular
                pair = (a, c)
                if pair in seen:
                    continue
                seen.add(pair)

                # Combined direction
                dir_map = {"positive": 1, "negative": -1, "mixed": 0}
                prod = dir_map.get(rule_ab.direction, 0) * dir_map.get(rule_bc.direction, 0)
                direction = "positive" if prod > 0 else ("negative" if prod < 0 else "mixed")
                chain_conf = rule_ab.confidence * rule_bc.confidence
                via_phrase = f"via {b}"

                if direction == "positive":
                    rule_str = f"if {a} increases then {c} increases {via_phrase}"
                elif direction == "negative":
                    rule_str = f"if {a} increases then {c} decreases {via_phrase}"
                else:
                    rule_str = f"{a} indirectly affects {c} {via_phrase}"

                hyps.append(ChainHypothesis(
                    rule=rule_str,
                    concepts=[a, c, b],
                    confidence=chain_conf,
                    supporting_evidence=min(
                        rule_ab.observations, rule_bc.observations
                    ),
                    contradicting_evidence=0,
                    chain_type="transitive",
                ))

        return hyps

    # ── Mediator hypotheses ───────────────────────────────────────────────────

    def _mediator_hyps(self, causal_rules: List) -> List[ChainHypothesis]:
        """When A→B direction flips across observations, generate mediator hyp."""
        hyps: List[ChainHypothesis] = []

        for rule in causal_rules:
            key = (rule.cause, rule.effect)
            prev_dir = self._last_directions.get(key)

            if prev_dir is not None and prev_dir != rule.direction:
                self._flip_count[key] = self._flip_count.get(key, 0) + 1
            self._last_directions[key] = rule.direction

            if self._flip_count.get(key, 0) >= MEDIATOR_FLIP_THRESHOLD:
                rule_str = (
                    f"effect of {rule.cause} on {rule.effect} is context-dependent "
                    f"(mediating variable suspected)"
                )
                hyps.append(ChainHypothesis(
                    rule=rule_str,
                    concepts=[rule.cause, rule.effect],
                    confidence=0.4,
                    supporting_evidence=self._flip_count[key],
                    contradicting_evidence=0,
                    chain_type="mediator",
                ))
                # Reset to avoid continuous spam
                self._flip_count[key] = 0

        return hyps

    # ── Diversity hypotheses ──────────────────────────────────────────────────

    def _diversity_hyps(
        self,
        all_hypotheses: List,
        causal_rules:   List,
    ) -> List[ChainHypothesis]:
        """Force hypothesis generation about under-represented concepts."""
        concept_counts: Counter = Counter()
        for h in all_hypotheses:
            for c in getattr(h, "concepts", []):
                concept_counts[c] += 1

        if not concept_counts:
            return []

        total = sum(concept_counts.values())
        dominant = {c for c, n in concept_counts.items() if n / total > DIVERSITY_DOMINANCE_THRESHOLD}
        if not dominant:
            return []

        # Find concepts in causal rules that are under-represented
        all_rule_concepts = {c for rule in causal_rules for c in [rule.cause, rule.effect]}
        under = all_rule_concepts - dominant - {c for c, n in concept_counts.items() if n > 0}

        hyps: List[ChainHypothesis] = []
        for concept in list(under)[:3]:
            # Find a causal rule featuring this concept
            rule = next(
                (r for r in causal_rules if r.cause == concept or r.effect == concept),
                None
            )
            if rule is None:
                continue
            other = rule.effect if rule.cause == concept else rule.cause
            rule_str = f"[diversity] {concept} has unexplored effects on {other}"
            hyps.append(ChainHypothesis(
                rule=rule_str,
                concepts=[concept, other],
                confidence=0.3,
                supporting_evidence=1,
                contradicting_evidence=0,
                chain_type="diversity",
            ))

        return hyps